version: '3'

services:
  backstage:
    image: 204173949765.dkr.ecr.ap-southeast-2.amazonaws.com/demo-backstage:latest
    ports:
      - "7007:7007"
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      APP_DOMAIN: "localhost"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      GITHUB_TOKEN: xxxxxxxx

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    ports:
      - "5432:5432"