version: '3'
services:
  backstage:
    image: demo-backstage:1.0.0
    ports:
      - "7007:7007"
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      BACKEND_URL: "http://xxxx:7007"
      APP_DOMAIN: "http://xxxx:3000"
      PGSSLMODE: allow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: xxxx
      GITHUB_TOKEN: xxxxxxxxxxxx
      AUTH_GITHUB_CLIENT_ID: xxxxxxxxxxxxxx
      AUTH_GITHUB_CLIENT_SECRET: xxxxxxxxxxxxxx

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: xxxxxxxx
    ports:
      - "5432:5432"